name: Build Samsung Calc APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y libgstreamer1.0-gstreamer-lite-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        # تثبيت مكتبة tkinter للسيرفر
        sudo apt-get install -y python3-tk tcl-dev tk-dev
        pip install --upgrade pip
        pip install --user --upgrade buildozer Cython==0.29.33

    - name: Build with Buildozer
      run: |
        # أمر البناء مع قبول الرخص تلقائياً
        yes | buildozer -v android debug
      continue-on-error: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Samsung-Calculator-Debug
        path: bin/*.apk
